_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "./myILOD/params/model_final.pth"
  ROI_HEADS:
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
DATALOADER:
  NUM_WORKERS: 4
DATASETS:
  TRAIN: ('emm+5.json', )
  TEST: ('voc_2007_test', )
  MEMORY: ('emm15_50img.json', )
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (6000,)
  MAX_ITER: 8000
  WARMUP_ITERS: 100
TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: "./output/default"
SEED: 9999
